run_cases_3d now using reuse_wind_case

diff --git a/openfoam_batch/reuse_wind_case b/openfoam_batch/reuse_wind_case
--- a/openfoam_batch/reuse_wind_case
+++ b/openfoam_batch/reuse_wind_case
@@ -10,14 +10,14 @@ original_case="W1"
 original_speed="1"
 output_dir="$home_dir"
 base_case=""
+return_val=0
 
 usage() { 
     echo -e "Usage: $0 [OPTIONS] V1 V2 ..."
     echo -e "  V1 V2 ... New velocity values"
     echo -e "  -c CASE_DIR\n\tDirectory for original case [default W1]"
-    echo -e "  -v CASE_VEL"
+    echo -e "  -v CASE_VEL\n\tInflow wind speed of original case [default 1]"
     echo -e "  -b BASE_CASE\n\tDirectory for base case [default CASE_DIR]"
-    echo -e "\tInflow wind speed of original case [default 1]"
     echo -e "  -o OUT_DIR\n\tOutput directory [default ./]"
     echo -e "  -h\n\tPrint this help and exit"
     echo -e "\tNew cases will be created in OUT_DIR/WV1/, OUT_DIR/WV2/, etc"
@@ -55,19 +55,22 @@ then
 fi
 
 # Get current U, p, k, epsilon, nut
-# First, convert case to ascii
+# First, convert case to ascii (sed -i command replaces symlink with file)
 cd $original_case
 latest_time=$( foamListTimes -latestTime )
+sed -i '' system/controlDict
+existing_format=$( foamDictionary -entry 'writeFormat' -value system/controlDict)
 foamDictionary -entry 'writeFormat' -set "ascii" system/controlDict
 foamFormatConvert -latestTime -noConstant
+foamDictionary -entry 'writeFormat' -set "$existing_format" system/controlDict
 
 declare -a set_fields=("U" "p" "k" "epsilon" "nut")
 for field in "${set_fields[@]}"; do
-    foamDictionary -entry 'internalField' -value "${latest_time}/U" > "${original_case}/temp${field}.txt"
+    foamDictionary -entry 'internalField' -value "${latest_time}/${field}" > "${original_case}/temp${field}.txt"
 done
 
 for wind_speed in "$@"; do
-    wind_directory="${output_dir}/$w"
+    wind_directory="${output_dir}/W${wind_speed}"
     ratio=$( echo "scale=5; ${wind_speed}/${original_speed}" | bc )
     ratio_sq=$( echo "$ratio*$ratio" | bc )
     ratio_cu=$( echo "${ratio_sq}*$ratio" | bc )
@@ -103,12 +106,25 @@ for wind_speed in "$@"; do
             nut) mult="$ratio" ;;
             k|p) mult="$ratio_sq" ;;
             epsilon) mult="$ratio_cu" ;;
-            *) echo "Multiplier not found for ${field}!"; exit 1 ;;
+            *) echo "Multiplier not found for ${field}!" >&2; exit 1 ;;
         esac
 
         ffile="${field}mod.txt"
         awk 'NR<=3 {print; next}; /^[^\)]/  { print $1*'"$mult"'; next; }; 1' "${original_case}/temp${field}.txt" > "$ffile"
-        foamDictionary -entry 'internalField' -set "\#include \"${ffile}\"" "$field" > /dev/null
-        # rm "$ffile"
+        foamDictionary -entry 'internalField' -set "#include \"${ffile}\"" "$field" > /dev/null
+        rm "$ffile"
     done
+    
+    cd "$wind_directory"
+    echo -en "\tRunning simpleFoam for reuse case..."
+    simpleFoam > simpleFoam.log 2> simpleFoam.err
+    simple_success="$?"
+    if [ "$simple_success" -gt 0 ]; then
+        echo " failed!"
+    else
+        simple_iter=$(  foamListTimes -latestTime )
+        echo " converged in ${simple_iter} iterations."
+    fi
+    return_val=$( echo "${simple_success} + ${return_val}" | bc )
 done
+exit $return_val
diff --git a/openfoam_batch/run_cases_3d b/openfoam_batch/run_cases_3d
--- a/openfoam_batch/run_cases_3d
+++ b/openfoam_batch/run_cases_3d
@@ -207,70 +207,93 @@ for stl_dir in "$@"; do
     echo "ABL_PARAMS: $abl_params"
 
     # Loop over wind speeds
-    for (( w=1; w<=15; w+=$wind_delta )); do
+    #for (( w=1; w<=15; w+=$wind_delta )); do
+    w=1
 
-        # Calculate k, epsilon
-        k_epsilon=($(python $python_directory/abl_k_epsilon.py -U $w $abl_params))
-        k_abl="${k_epsilon[0]}"
-        eps_abl="${k_epsilon[1]}"
-        echo "K_EPSILON: $k_abl $eps_abl"
+    # Calculate k, epsilon
+    k_epsilon=($(python $python_directory/abl_k_epsilon.py -U $w $abl_params))
+    k_abl="${k_epsilon[0]}"
+    eps_abl="${k_epsilon[1]}"
+    echo "K_EPSILON: $k_abl $eps_abl"
 
-        wind_directory="${case_dir}/W${w}"
-        # Create system folder, symlinks from base case
-        create_base_case $wind_directory $base_case/base
-        ln -s ${simpleFoam_dir}/constant/polyMesh $wind_directory/constant/polyMesh
+    wind_directory="${case_dir}/W${w}"
+    # Create system folder, symlinks from base case
+    create_base_case $wind_directory $base_case/base
+    ln -s ${simpleFoam_dir}/constant/polyMesh $wind_directory/constant/polyMesh
 
-        cd $wind_directory
-        if [ $end_iter -gt 0 ]; then
-            sed -i -e "s/endTime\s\{1,\}[0-9]*/endTime\t${end_iter}/g" system/controlDict
-        fi
-        if [ $write_iter -gt 0 ]; then
-            sed -i -e "s/writeInterval\s\{1,\}[0-9]*/writeInterval\t${write_iter}/g" system/controlDict
-        fi
+    cd $wind_directory
+    if [ $end_iter -gt 0 ]; then
+        sed -i -e "s/endTime\s\{1,\}[0-9]*/endTime\t${end_iter}/g" system/controlDict
+    fi
+    if [ $write_iter -gt 0 ]; then
+        sed -i -e "s/writeInterval\s\{1,\}[0-9]*/writeInterval\t${write_iter}/g" system/controlDict
+    fi
 
-        # Copy initial conditions, change wind speed
-        cp -r $base_case/simpleFoam/0.orig $wind_directory/0
-        sed -i "s/WINDSPEED/$w/" 0/include/ABLConditions
-        sed -i "s/INLETK/${k_abl}/" 0/k
-        sed -i "s/INLETEPSILON/${eps_abl}/" 0/epsilon
-        echo -en "\tCase setup complete: W=$w, running simpleFoam..."
-        simpleFoam > simpleFoam.log 2> simpleFoam.err
+    # Copy initial conditions, change wind speed
+    cp -r $base_case/simpleFoam/0.orig $wind_directory/0
+    sed -i "s/WINDSPEED/$w/" 0/include/ABLConditions
+    sed -i "s/INLETK/${k_abl}/" 0/k
+    sed -i "s/INLETEPSILON/${eps_abl}/" 0/epsilon
+    echo -en "\tCase setup complete: W=$w, running simpleFoam..."
+    simpleFoam > simpleFoam.log 2> simpleFoam.err
+    if [ "$?" -gt 0 ]; then
+        echo " failed!"
+        continue
+    fi
+    first_converged=$( foamListTimes -latestTime ) # ls -d */ | sed 's:\([0-9]\+\).*:\1:g' | sort -n | tail -1)
+    echo " converged in ${first_converged} iterations."
+
+    if [ -n "$second_solver" ]; then
+        # We also have a higher-order case
+        echo -en "\tRunning second solver simpleFoam..."
+        create_base_case $wind_directory $base_case/$second_solver -fn
+        simpleFoam > simpleFoam2.log 2> simpleFoam2.err
         if [ "$?" -gt 0 ]; then
             echo " failed!"
-            continue
+        else
+            second_converged=$(  foamListTimes -latestTime ) # ls -d */ | sed 's:\([0-9]\+\).*:\1:g' | sort -n | tail -1)
+            echo " converged in ${second_converged} iterations."
         fi
-        first_converged=$(ls -d */ | sed 's:\([0-9]\+\).*:\1:g' | sort -n | tail -1)
-        echo " converged in ${first_converged} iterations."
+    fi
+    
+    cd $wind_directory
+    touch hill.foam
 
-        if [ -n "$second_solver" ]; then
-            # We also have a higher-order case
-            echo -en "\tRunning second solver simpleFoam..."
-            create_base_case $wind_directory $base_case/$second_solver -fn
-            simpleFoam > simpleFoam2.log 2> simpleFoam2.err
-            if [ "$?" -gt 0 ]; then
-                echo " failed!"
-            else
-                second_converged=$(ls -d */ | sed 's:\([0-9]\+\).*:\1:g' | sort -n | tail -1)
-                echo " converged in ${second_converged} iterations."
-            fi
+    if [ "$regrid" -gt 0 ]
+    then
+        latest_time=$( foamListTimes -latestTime )
+        echo -en "\tResampling results onto test grid..."
+        printf -v csv_file "$csv_dir/%s_W%02d" $casename $w
+        python "${python_directory}/resample.py" --three-d --case-dir $wind_directory \
+            --mesh-dir $reGrid_dir --case-foam hill.foam --outfile $csv_file --time $latest_time
+        if [ "$?" -gt 0 ]; then
+            echo " failed!"
+        else
+            echo " done."
         fi
-        
-        cd $wind_directory
-        touch hill.foam
-
-        if [ $regrid -gt 0 ]
+    fi
+    
+    cd $home_dir
+    w=$( echo "$w+$wind_delta" | bc )
+    for (( w=$w; w<=15; w+=$wind_delta )); do
+        ./reuse_wind_case -c "${case_dir}/W1" -v 1 -o "$case_dir" $w
+        if [ "$?" -eq 0 ] && [ "$regrid" -gt 0 ]
         then
-            echo -en "\tResampling results onto test grid..."
+            wind_directory="${case_dir}/W${w}"
+            cd $wind_directory
+            touch hill.foam
+            latest_time=$( foamListTimes -latestTime )
             printf -v csv_file "$csv_dir/%s_W%02d" $casename $w
+            echo -en "\tCreating csv for t=$latest_time to $csv_file..."
             python "${python_directory}/resample.py" --three-d --case-dir $wind_directory \
-                --mesh-dir $reGrid_dir --case-foam hill.foam --outfile $csv_file
+                --mesh-dir $reGrid_dir --case-foam hill.foam --outfile $csv_file --time $latest_time
             if [ "$?" -gt 0 ]; then
                 echo " failed!"
             else
                 echo " done."
             fi
         fi
+        cd $home_dir
     done
-    cd $home_dir
 done
 
