Streamlined run_cases to use make_csvs and reuse_wind_cases mroe efficiently

diff --git a/openfoam_batch/run_cases_3d b/openfoam_batch/run_cases_3d
--- a/openfoam_batch/run_cases_3d
+++ b/openfoam_batch/run_cases_3d
@@ -100,10 +100,11 @@ python_directory=$home_dir/python
 
 # Loop over case_directories, create new directory for each case
 for stl_dir in "$@"; do
+    stl_dir=$( check_path "$stl_dir" "$home_dir" ) || continue
     casename=$(basename -- "$stl_dir")
-    stl_file=${home_dir}/${stl_dir}/${casename}.stl
-    terrainDict_file=${home_dir}/${stl_dir}/terrainDict
-    ylim_file=${home_dir}/${stl_dir}/YLIMS
+    stl_file="${stl_dir}/${casename}.stl"
+    terrainDict_file="${stl_dir}/terrainDict"
+    ylim_file="${stl_dir}/YLIMS"
     
     check_files $stl_file $terrainDict_file $ylim_file
     if [ $? -gt 0 ]; then
@@ -241,8 +242,15 @@ for stl_dir in "$@"; do
         echo " failed!"
         continue
     fi
-    first_converged=$( foamListTimes -latestTime ) # ls -d */ | sed 's:\([0-9]\+\).*:\1:g' | sort -n | tail -1)
-    echo " converged in ${first_converged} iterations."
+    first_iterations=$( foamListTimes -latestTime ) 
+    first_converged=$( check_converged )
+    if [ "$first_converged" -eq 0 ]; then
+        echo " did not converge in max iterations."
+        echo "unconverged" >> simpleFoam.err
+        # We still try second solver anyway if we have one
+        [ ! -n "$second_solver" ] && continue
+    fi
+    echo " converged in ${first_iterations} iterations."
 
     if [ -n "$second_solver" ]; then
         # We also have a higher-order case
@@ -254,50 +262,30 @@ for stl_dir in "$@"; do
             echo " failed!"
 	    continue
         else
-            second_converged=$(  foamListTimes -latestTime ) # ls -d */ | sed 's:\([0-9]\+\).*:\1:g' | sort -n | tail -1)
-            echo " converged in ${second_converged} iterations."
-            rm -r "${wind_directory}/${first_converged}"
+            second_iterations=$(  foamListTimes -latestTime ) 
+            second_converged=$( check_converged )
+            if [ "$second_converged" -eq 0 ]; then
+                echo " did not converge in max iterations."
+                echo "unconverged" >> simpleFoam2.err
+                continue
+            fi
+            echo " converged in ${second_iterations} iterations."
+            rm -r "${wind_directory}/${first_iterations}"
         fi
     fi
-    
-    cd $wind_directory
-    touch hill.foam
+    touch "${wind_directory}/hill.foam"
 
-    if [ "$regrid" -gt 0 ]
-    then
-        latest_time=$( foamListTimes -latestTime )
-        echo -en "\tResampling results onto test grid..."
-        printf -v csv_file "$csv_dir/%s_W%02d" $casename $w
-        python "${python_directory}/resample.py" --three-d --case-dir $wind_directory \
-            --mesh-dir $reGrid_dir --case-foam hill.foam --outfile $csv_file --time $latest_time
-        if [ "$?" -gt 0 ]; then
-            echo " failed!"
-        else
-            echo " done."
-        fi
-    fi
-    
     cd $home_dir
     w=$( echo "$w+$wind_delta" | bc )
+    wlist=''
     for (( w=$w; w<=15; w+=$wind_delta )); do
-        ./reuse_wind_case -c "${case_dir}/W1" -v 1 -o "$case_dir" $w
-        if [ "$?" -eq 0 ] && [ "$regrid" -gt 0 ]
-        then
-            wind_directory="${case_dir}/W${w}"
-            cd $wind_directory
-            touch hill.foam
-            latest_time=$( foamListTimes -latestTime )
-            printf -v csv_file "$csv_dir/%s_W%02d" $casename $w
-            echo -en "\tCreating csv for t=$latest_time to $csv_file..."
-            python "${python_directory}/resample.py" --three-d --case-dir $wind_directory \
-                --mesh-dir $reGrid_dir --case-foam hill.foam --outfile $csv_file --time $latest_time
-            if [ "$?" -gt 0 ]; then
-                echo " failed!"
-            else
-                echo " done."
-            fi
-        fi
-        cd $home_dir
+        wlist="${wlist} ${w}"
     done
+    ./reuse_wind_case -c "${case_dir}/W1" -v 1 -o "$case_dir" $wlist
+    echo "\tReuse wind case returned: $? failures"
+
+    if [ "$regrid" -gt 0 ]; then
+        make_csvs.sh -c "$csv_dir" -p "$python_directory" -w "$wind_delta" "$case_dir"
+    fi
 done
 
