Created shared_functions, updated output formatting

diff --git a/openfoam_batch/run_cases_3d b/openfoam_batch/run_cases_3d
--- a/openfoam_batch/run_cases_3d
+++ b/openfoam_batch/run_cases_3d
@@ -7,13 +7,16 @@ OPTIND=1
 stl_dir="stl/"
 base_dir="base_case3d/"
 csv_dir="csv3d/"
-DW=20
-HOMEDIR=$(pwd)
-ENDITER=-1
-WRITEITER=-1
+wind_delta=20
+home_dir=$(pwd)
+end_iter=-1
+write_iter=-1
+
+# Source shared functions ( 'create_base_case' and 'check_files' )
+source shared_functions.sh
 
 usage() { 
-    echo -e "Usage: $0 [OPTION] stl_file1 stl_file2 ..."
+    echo -e "Usage: $0 [OPTION] stl_dir1 stl_dir2 ..."
     # echo -e "  -s stl_dir\n\tDirectory of stl files"
     echo -e "  -c csv_dir\n\tDirectory to output csv files"
     echo -e "  -b base_dir\n\tlocation of base case directory"
@@ -24,7 +27,6 @@ usage() {
     echo -e "\twriteInterval for simpleFoam (default to existing value from controlDict)"
     echo -e "  -h"
     echo -e "\tprint this help and exit"
-    exit 0;
 }
 
 while getopts "c:b:w:e:i:h" opt; do
@@ -34,144 +36,179 @@ while getopts "c:b:w:e:i:h" opt; do
             ;;
         b)  base_dir=$OPTARG
             ;;
-        w)  DW=$OPTARG
+        w)  wind_delta=$OPTARG
             ;;
-        e)  ENDITER=$OPTARG
+        e)  end_iter=$OPTARG
             ;;
-        i)  WRITEITER=$OPTARG
+        i)  write_iter=$OPTARG
             ;;
-        h | *)
+        h)
             usage
+            exit 0
+            ;;
+        *)
+            usage >&2
+            exit 1
             ;;
     esac
 done
 shift $(expr $OPTIND - 1 )
 
 if [ "$#" -lt 1 ]; then
-    echo "ERROR: No stl files supplied"
-    usage
+    echo "ERROR: No stl directories supplied" >&2
+    usage >&2
+    exit 1
 fi
 
-# The remaining arguments are the csv files
-constant_files=(transportProperties turbulenceProperties)
-system_files=(controlDict fvSchemes fvSolution)
-BASECASES=$HOMEDIR/$base_dir
-PYDIR=$HOMEDIR/python
+# Check openFOAM version
+if ! type simpleFoam &> /dev/null 
+then
+    echo "ERROR: command simpleFoam not found, have you sourced OpenFOAM bashrc?" >&2
+    exit 1
+fi
+openfoam_build=$(simpleFoam -help | sed -n -e '/Build:\s/{s/.*://p}')
+openfoam_major_version=$(echo $openfoam_build | head -c 1) 
+echo "OpenFOAM version $openfoam_major_version found, build $openfoam_build"
+case "$openfoam_major_version" in
+    5) snappy_dict="snappyHexMeshDict"
+        ;;
+    4) snappy_dict="snappyHexMeshDict_v4"
+        ;;
+    *)
+        echo "ERROR: OpenFOAM major version not supported/recognized." >&2
+        exit 1
+        ;;
+esac
+
+# The remaining arguments are the stl directories
+base_case=$home_dir/$base_dir
+python_directory=$home_dir/python
 mkdir -p $csv_dir
 
-create_base_case()
-{
-    local f
-    # Argument 1 is the case name directory, arg 2 is the file source
-    mkdir -p $1/system
-    for f in ${system_files[@]}; do
-        ln -s $2/system/$f $1/system/$f
-    done
-    
-    mkdir -p $1/constant
-    for f in ${constant_files[@]}; do
-        ln -s $2/constant/$f $1/constant/$f
-    done
-}
 
-# Loop over stl files, create new directory for each case
-for stl_file in "$@"; do
-    basename=$(basename -- "$stl_file")
-    extension="${basename##*.}"
-    casename="${basename%.*}"
+# Loop over case_directories, create new directory for each case
+for stl_dir in "$@"; do
+    casename=$(basename -- "$stl_dir")
+    stl_file=${home_dir}/${stl_dir}/${casename}.stl
+    terrainDict_file=${home_dir}/${stl_dir}/terrainDict
+    ylim_file=${home_dir}/${stl_dir}/YLIMS
     
-    echo "Creating new case ${casename} based on ${stl_file}"
-    CASEDIR=${HOMEDIR}/cases3d/${casename}
-    mkdir -p $CASEDIR
+    check_files $stl_file $terrainDict_file $ylim_file
+    if [ $? -gt 0 ]; then
+        echo "Case file not found, skipping case $casename"
+        continue
+    fi
+    
+    echo "Creating new case ${casename} based on ${stl_dir}"
+    case_dir=${home_dir}/cases3d/${casename}
+    mkdir -p $case_dir
 
-    SIMPLEDIR="${CASEDIR}/simpleFoam"
-    GRIDDIR="${CASEDIR}/reGrid"
-    STLOUT="${CASEDIR}/${casename}.stl"
+    simpleFoam_dir="${case_dir}/simpleFoam"
+    reGrid_dir="${case_dir}/reGrid"
+    stl_case_file="${case_dir}/${casename}.stl"
 
-    # Use python script to generate new stl file (reset origin) and terrainDict
-    # Y limits should be only thing printed (bit dodge though...)
-    YLIMS=$(python python/stl_terrainDict.py -si ${stl_file} -so ${STLOUT} \
-        -do ${CASEDIR}/terrainDict --pad-z 3.0)
-    echo "YLIMS = ${YLIMS}"
-    YLIMS=($YLIMS)      #<- This converts string to array to access elements ${YLIMS[i]}
+    ln -s $stl_file $stl_case_file
+    ln -s $terrainDict_file ${case_dir}/terrainDict
     
-    
+    # Get y_limits as an array to access elements ${y_limits[i]}
+    y_limits=( $( < $ylim_file ) )    
+
     # Create simpleFoam directory for running simpleFoam
-    create_base_case $SIMPLEDIR $BASECASES/base
-    ln -s ${CASEDIR}/terrainDict $SIMPLEDIR/system/terrainDict
+    create_base_case $simpleFoam_dir $base_case/base
+    ln -s ${CASEDIR}/terrainDict $simpleFoam_dir/system/terrainDict
 
-    mkdir -p $SIMPLEDIR/constant/triSurface
-    ln -s $STLOUT $SIMPLEDIR/constant/triSurface/${casename}.stl
-    ln -s $BASECASES/simpleFoam/system/blockMeshDict \
-        $SIMPLEDIR/system/blockMeshDict
-    ln -s $BASECASES/simpleFoam/system/snappyHexMeshDict \
-        $SIMPLEDIR/system/snappyHexMeshDict
+    mkdir -p $simpleFoam_dir/constant/triSurface
+    ln -s $stl_case_file $simpleFoam_dir/constant/triSurface/${casename}.stl
+    ln -s $base_case/simpleFoam/system/blockMeshDict \
+        $simpleFoam_dir/system/blockMeshDict
+    ln -s $base_case/simpleFoam/system/${snappy_dict} \
+        $simpleFoam_dir/system/snappyHexMeshDict
 
     # Create reGrid directory for output resampling onto regular grid
-    create_base_case $GRIDDIR $BASECASES/base
-    ln -s $BASECASES/reGrid/system/blockMeshDict \
-        $GRIDDIR/system/blockMeshDict
-    ln -s ${CASEDIR}/terrainDict $GRIDDIR/system/terrainDict
-    ln -s $BASECASES/reGrid/Allclean $GRIDDIR/Allclean
+    create_base_case $reGrid_dir $base_case/base
+    ln -s $base_case/reGrid/system/blockMeshDict \
+        $reGrid_dir/system/blockMeshDict
+    ln -s ${CASEDIR}/terrainDict $reGrid_dir/system/terrainDict
+    ln -s $base_case/reGrid/Allclean $reGrid_dir/Allclean
    
 
     # Build mesh
     echo -ne "\tBuilding mesh..."
-    cd $SIMPLEDIR
+    cd $simpleFoam_dir
 
     blockMesh > blockMesh.log 2> blockMesh.err
-    snappyHexMesh -overwrite > snappyHexMesh.log 
+    snappyHexMesh -overwrite > snappyHexMesh.log 2> snappyHexMesh.err
 
-    echo " done."
+    if [ $? -ne 0 ]
+    then
+        echo " snappyHexMesh failed. Error report follows:"
+        cat snappyHexMesh.err
+        continue
+    else
+        echo " done. Final mesh properties:"
+        cat snappyHexMesh.log | tail -14
+    fi
 
     echo -en "\tBuilding resampled (regular) mesh for final output..."
-    cd $GRIDDIR
+    cd $reGrid_dir
     ./Allclean
     blockMesh > blockMesh.log 2> blockMesh.err
-    touch testgrid.foam
+
+    if [ $? -ne 0 ]
+    then
+        echo " failed. Error report follows:"
+        cat blockMesh.err
+        echo -e "\tMoving to next case."
+        continue
+    fi
     echo " done."
+    touch testgrid.foam
 
     # Loop over wind speeds
-    for (( w=1; w<=15; w+=$DW )); do
+    for (( w=1; w<=15; w+=$wind_delta )); do
 
         # Calculate k, epsilon
-        K_EPS=($(python $PYDIR/abl_k_epsilon.py -U $w))
+        k_epsilon=($(python $python_directory/abl_k_epsilon.py -U $w))
 
-        WDIR="${CASEDIR}/W${w}"
+        wind_directory="${CASEDIR}/W${w}"
         # Create system folder, symlinks from base case
-        create_base_case $WDIR $BASECASES/base
-        ln -s ${SIMPLEDIR}/constant/polyMesh $WDIR/constant/polyMesh
+        create_base_case $wind_directory $base_case/base
+        ln -s ${simpleFoam_dir}/constant/polyMesh $wind_directory/constant/polyMesh
 
         # Copy initial conditions, change wind speed
-        cd $WDIR
-        if [ $ENDITER -gt 0 ]; then
-            sed -i -e "s/endTime\s\{1,\}[0-9]*/endTime\t${ENDITER}/g" system/controlDict
+        cd $wind_directory
+        if [ $end_iter -gt 0 ]; then
+            sed -i -e "s/endTime\s\{1,\}[0-9]*/endTime\t${end_iter}/g" system/controlDict
         fi
-        if [ $WRITEITER -gt 0 ]; then
-            sed -i -e "s/writeInterval\s\{1,\}[0-9]*/writeInterval\t${WRITEITER}/g" system/controlDict
+        if [ $write_iter -gt 0 ]; then
+            sed -i -e "s/writeInterval\s\{1,\}[0-9]*/writeInterval\t${write_iter}/g" system/controlDict
         fi
 
-        cp -r $BASECASES/simpleFoam/0.orig.k_eps $WDIR/0
+        cp -r $base_case/simpleFoam/0.orig $wind_directory/0
         sed -i "s/WINDSPEED/$w/" 0/include/ABLConditions
-        sed -i "s/INLETK/${K_EPS[0]}/" 0/k
-        sed -i "s/INLETEPSILON/${K_EPS[1]}/" 0/epsilon
+        sed -i "s/INLETK/${k_epsilon[0]}/" 0/k
+        sed -i "s/INLETEPSILON/${k_epsilon[1]}/" 0/epsilon
         echo -en "\tCase setup complete: W=$w, running simpleFoam..."
         simpleFoam > simpleFoam.log 2> simpleFoam.err
         if [ "$?" -gt 0 ]; then
-            echo " failed. Moving to next case"
-        else
-            echo " done."
-            cd $WDIR
-            touch hill.foam
+            echo " failed. Moving to next case."
+            continue
+        fi
+        
+        echo " done."
+        cd $wind_directory
+        touch hill.foam
 
-            echo -n "Resampling grid onto test grid..."
-            printf -v CSVFILE "%s_W%02d" $casename $w
-            python "${HOMEDIR}/python/resample.py" --three-d --case-dir $WDIR --mesh-dir $GRIDDIR \
-                --case-foam hill.foam --outfile "$HOMEDIR/$csv_dir/$CSVFILE"
+        echo -en "\tResampling results onto test grid..."
+        printf -v csv_file "$home_dir/$csv_dir/%s_W%02d" $casename $w
+        python "${python_directory}/resample.py" --three-d --case-dir $wind_directory \
+            --mesh-dir $reGrid_dir --case-foam hill.foam --outfile $csv_file
+        if [ "$?" -gt 0 ]; then
+            echo " failed. Moving to next case."
+        else
             echo " done."
         fi
     done
-
-    cd $HOMEDIR
+    cd $home_dir
 done
 
