Changed 3D case for static pressure boundaries, no testing

diff --git a/openfoam_batch/run_cases_3d b/openfoam_batch/run_cases_3d
--- a/openfoam_batch/run_cases_3d
+++ b/openfoam_batch/run_cases_3d
@@ -11,6 +11,8 @@ wind_delta=20
 home_dir=$(pwd)
 end_iter=-1
 write_iter=-1
+regrid=1
+build_mesh=1
 
 # Source shared functions ( 'create_base_case' and 'check_files' )
 source shared_functions.sh
@@ -25,11 +27,15 @@ usage() {
     echo -e "\tendTime for simpleFoam (default to existing value from controlDict)"
     echo -e "  -i write_interval"
     echo -e "\twriteInterval for simpleFoam (default to existing value from controlDict)"
+    echo -e "  -g [0/1]"
+    echo -e "\tgenerate regridded output (default 1)"
+    echo -e "  -s [0/1]"
+    echo -e "\trerun snappyHexMesh to generate new mesh (default 1)"
     echo -e "  -h"
     echo -e "\tprint this help and exit"
 }
 
-while getopts "c:b:w:e:i:h" opt; do
+while getopts "c:b:w:e:i:s:h" opt; do
     case "$opt" in
         # s)  stl_dir=$OPTARG ;;
         c)  csv_dir=$OPTARG
@@ -41,6 +47,8 @@ while getopts "c:b:w:e:i:h" opt; do
         e)  end_iter=$OPTARG
             ;;
         i)  write_iter=$OPTARG
+            ;;
+        s)  build_mesh=$OPTARG
             ;;
         h)
             usage
@@ -115,7 +123,7 @@ for stl_dir in "$@"; do
 
     # Create simpleFoam directory for running simpleFoam
     create_base_case $simpleFoam_dir $base_case/base
-    ln -s ${CASEDIR}/terrainDict $simpleFoam_dir/system/terrainDict
+    ln -s ${case_dir}/terrainDict $simpleFoam_dir/system/terrainDict
 
     mkdir -p $simpleFoam_dir/constant/triSurface
     ln -s $stl_case_file $simpleFoam_dir/constant/triSurface/${casename}.stl
@@ -128,47 +136,52 @@ for stl_dir in "$@"; do
     create_base_case $reGrid_dir $base_case/base
     ln -s $base_case/reGrid/system/blockMeshDict \
         $reGrid_dir/system/blockMeshDict
-    ln -s ${CASEDIR}/terrainDict $reGrid_dir/system/terrainDict
+    ln -s ${case_dir}/terrainDict $reGrid_dir/system/terrainDict
     ln -s $base_case/reGrid/Allclean $reGrid_dir/Allclean
    
 
-    # Build mesh
-    echo -ne "\tBuilding mesh..."
-    cd $simpleFoam_dir
-
-    blockMesh > blockMesh.log 2> blockMesh.err
-    if [ $? -ne 0 ]
+    if [ $build_mesh -gt 0 ]
     then
-        echo " blockMesh failed. Skipping ${casename}. Error report:"
-        cat blockMesh.err
-        continue
+        # Build mesh
+        echo -ne "\tBuilding mesh..."
+        cd $simpleFoam_dir
+
+        blockMesh > blockMesh.log 2> blockMesh.err
+        if [ $? -ne 0 ]
+        then
+            echo " blockMesh failed. Skipping ${casename}. Error report:"
+            cat blockMesh.err
+            continue
+        fi
+
+        snappyHexMesh -overwrite > snappyHexMesh.log 2> snappyHexMesh.err
+        if [ $? -ne 0 ]
+        then
+            echo " snappyHexMesh failed. Skipping ${casename}. Error report:"
+            cat snappyHexMesh.err
+            continue
+        else
+            echo " done. Final mesh properties:"
+            cat snappyHexMesh.log | tail -14
+        fi
+
+        echo -en "\tBuilding resampled (regular) mesh for final output..."
+        cd $reGrid_dir
+        ./Allclean
+        blockMesh > blockMesh.log 2> blockMesh.err
+
+        if [ $? -ne 0 ]
+        then
+            echo " failed. Error report:"
+            cat blockMesh.err
+            echo -e "\tMoving to next case."
+            continue
+        fi
+        echo " done."
+        touch testgrid.foam
     fi
 
-    snappyHexMesh -overwrite > snappyHexMesh.log 2> snappyHexMesh.err
-    if [ $? -ne 0 ]
-    then
-        echo " snappyHexMesh failed. Skipping ${casename}. Error report:"
-        cat snappyHexMesh.err
-        continue
-    else
-        echo " done. Final mesh properties:"
-        cat snappyHexMesh.log | tail -14
-    fi
-
-    echo -en "\tBuilding resampled (regular) mesh for final output..."
-    cd $reGrid_dir
-    ./Allclean
-    blockMesh > blockMesh.log 2> blockMesh.err
-
-    if [ $? -ne 0 ]
-    then
-        echo " failed. Error report:"
-        cat blockMesh.err
-        echo -e "\tMoving to next case."
-        continue
-    fi
-    echo " done."
-    touch testgrid.foam
+    cd $case_dir
 
     # Loop over wind speeds
     for (( w=1; w<=15; w+=$wind_delta )); do
@@ -176,7 +189,7 @@ for stl_dir in "$@"; do
         # Calculate k, epsilon
         k_epsilon=($(python $python_directory/abl_k_epsilon.py -U $w))
 
-        wind_directory="${CASEDIR}/W${w}"
+        wind_directory="${case_dir}/W${w}"
         # Create system folder, symlinks from base case
         create_base_case $wind_directory $base_case/base
         ln -s ${simpleFoam_dir}/constant/polyMesh $wind_directory/constant/polyMesh
@@ -190,14 +203,14 @@ for stl_dir in "$@"; do
             sed -i -e "s/writeInterval\s\{1,\}[0-9]*/writeInterval\t${write_iter}/g" system/controlDict
         fi
 
-        cp -r $base_case/simpleFoam/0.orig $wind_directory/0
+        cp -r $base_case/simpleFoam/0.orig.static $wind_directory/0
         sed -i "s/WINDSPEED/$w/" 0/include/ABLConditions
         sed -i "s/INLETK/${k_epsilon[0]}/" 0/k
         sed -i "s/INLETEPSILON/${k_epsilon[1]}/" 0/epsilon
         echo -en "\tCase setup complete: W=$w, running simpleFoam..."
         simpleFoam > simpleFoam.log 2> simpleFoam.err
         if [ "$?" -gt 0 ]; then
-            echo " failed. Moving to next case."
+            echo " failed!"
             continue
         fi
         
@@ -205,14 +218,17 @@ for stl_dir in "$@"; do
         cd $wind_directory
         touch hill.foam
 
-        echo -en "\tResampling results onto test grid..."
-        printf -v csv_file "$home_dir/$csv_dir/%s_W%02d" $casename $w
-        python "${python_directory}/resample.py" --three-d --case-dir $wind_directory \
-            --mesh-dir $reGrid_dir --case-foam hill.foam --outfile $csv_file
-        if [ "$?" -gt 0 ]; then
-            echo " failed. Moving to next case."
-        else
-            echo " done."
+        if [ $regrid -gt 0 ]
+        then
+            echo -en "\tResampling results onto test grid..."
+            printf -v csv_file "$home_dir/$csv_dir/%s_W%02d" $casename $w
+            python "${python_directory}/resample.py" --three-d --case-dir $wind_directory \
+                --mesh-dir $reGrid_dir --case-foam hill.foam --outfile $csv_file
+            if [ "$?" -gt 0 ]; then
+                echo " failed!"
+            else
+                echo " done."
+            fi
         fi
     done
     cd $home_dir
