Fixed mesh issues, updated k, eps calcs

diff --git a/openfoam_batch/run_cases_3d b/openfoam_batch/run_cases_3d
--- a/openfoam_batch/run_cases_3d
+++ b/openfoam_batch/run_cases_3d
@@ -31,11 +31,12 @@ usage() {
     echo -e "\tgenerate regridded output (default 1)"
     echo -e "  -s [0/1]"
     echo -e "\trerun snappyHexMesh to generate new mesh (default 1)"
+    echo -e "  -2 casename\n\tHigher-order solver case"
     echo -e "  -h"
     echo -e "\tprint this help and exit"
 }
 
-while getopts "c:b:w:e:i:s:h" opt; do
+while getopts "c:b:w:e:i:s:2:h" opt; do
     case "$opt" in
         # s)  stl_dir=$OPTARG ;;
         c)  csv_dir=$OPTARG
@@ -49,6 +50,8 @@ while getopts "c:b:w:e:i:s:h" opt; do
         i)  write_iter=$OPTARG
             ;;
         s)  build_mesh=$OPTARG
+            ;;
+        2)  second_solver=$OPTARG
             ;;
         h)
             usage
@@ -78,9 +81,9 @@ openfoam_build=$(simpleFoam -help | sed -n -e '/Build:\s/{s/.*://p}')
 openfoam_major_version=$(echo $openfoam_build | head -c 1) 
 echo "OpenFOAM version $openfoam_major_version found, build $openfoam_build"
 case "$openfoam_major_version" in
-    5) stl_geometry='geometry\n{\n\thill_geometry\n\t{\n\t\ttype triSurfaceMesh;\n\t\tfile $:TERRAIN_DICT.STL_FILE;\n\t}\n};'
+    5) stl_geometry='geometry\n{\n\t$:TERRAIN_DICT.STL_FILE\n\t{\n\t\ttype triSurfaceMesh;\n\t\tname hill_geometry;\n\t}\n};'
         ;;
-    4) stl_geometry='geometry\n{\n\t$:TERRAIN_DICT.STL_FILE\n\t{\n\t\ttype triSurfaceMesh;\n\t\tname hill_geometry;\n\t}\n};'
+    4) stl_geometry='geometry\n{\n\thill_geometry\n\t{\n\t\ttype triSurfaceMesh;\n\t\tfile $:TERRAIN_DICT.STL_FILE;\n\t}\n};'
         ;;
     *)
         echo "ERROR: OpenFOAM major version not supported/recognized." >&2
@@ -167,6 +170,7 @@ for stl_dir in "$@"; do
             echo " done. Final mesh properties:"
             cat snappyHexMesh.log | tail -14
         fi
+        rm -rf ${simpleFoam_dir}/dynamicCode/
 
         echo -en "\tBuilding resampled (regular) mesh for final output..."
         cd $reGrid_dir
@@ -186,18 +190,34 @@ for stl_dir in "$@"; do
 
     cd $case_dir
 
+    # Read atmospheric variables to calculate k, eps
+    abl_file="${base_case}/simpleFoam/0.orig/include/ABLConditions"
+    abl_kappa=$( sed -n 's/^ *kappa *\([\.,0-9]*\).*/\1/p' $abl_file )
+    abl_Cmu=$( sed -n 's/^ *Cmu *\([\.,0-9]*\).*/\1/p' $abl_file )
+    abl_Zref=$( sed -n 's/^ *Zref *\([\.,0-9]*\).*/\1/p' $abl_file )
+    abl_z0=$( sed -n 's/^ *z0[^0-9]*\([\.,0-9]*\).*/\1/p' $abl_file )
+    abl_zGround=$( sed -n 's/^ *zGround[^0-9]*\([\.,0-9]*\).*/\1/p' $abl_file )
+    abl_params="-z 5.0 --Z-ref $abl_Zref -z0 $abl_z0 -zg $abl_zGround "
+    if [ -n "$abl_kappa" ]; then
+        abl_params="$abl_params -k $abl_kappa"
+    fi
+    if [ -n "$abl_Cmu" ]; then
+        abl_params="$abl_params -C $abl_Cmu"
+    fi
+    echo "ABL_PARAMS: $abl_params"
+
     # Loop over wind speeds
     for (( w=1; w<=15; w+=$wind_delta )); do
 
         # Calculate k, epsilon
-        k_epsilon=($(python $python_directory/abl_k_epsilon.py -U $w))
+        k_epsilon=($(python $python_directory/abl_k_epsilon.py -U $w $abl_params))
+        echo "K_EPSILON: ${k_epsilon[0]} ${k_epsilon[1]}"
 
         wind_directory="${case_dir}/W${w}"
         # Create system folder, symlinks from base case
         create_base_case $wind_directory $base_case/base
         ln -s ${simpleFoam_dir}/constant/polyMesh $wind_directory/constant/polyMesh
 
-        # Copy initial conditions, change wind speed
         cd $wind_directory
         if [ $end_iter -gt 0 ]; then
             sed -i -e "s/endTime\s\{1,\}[0-9]*/endTime\t${end_iter}/g" system/controlDict
@@ -206,6 +226,7 @@ for stl_dir in "$@"; do
             sed -i -e "s/writeInterval\s\{1,\}[0-9]*/writeInterval\t${write_iter}/g" system/controlDict
         fi
 
+        # Copy initial conditions, change wind speed
         cp -r $base_case/simpleFoam/0.orig $wind_directory/0
         sed -i "s/WINDSPEED/$w/" 0/include/ABLConditions
         sed -i "s/INLETK/${k_epsilon[0]}/" 0/k
@@ -216,8 +237,22 @@ for stl_dir in "$@"; do
             echo " failed!"
             continue
         fi
+        first_converged=$(ls -d */ | sed 's:\([0-9]\+\).*:\1:g' | sort -n | tail -1)
+        echo " converged in ${first_converged} iterations."
+
+        if [ -n "$second_solver" ]; then
+            # We also have a higher-order case
+            echo -en "\tRunning second solver simpleFoam..."
+            create_base_case $wind_directory $base_case/$second_solver -fn
+            simpleFoam > simpleFoam2.log 2> simpleFoam2.err
+            if [ "$?" -gt 0 ]; then
+                echo " failed!"
+            else
+                second_converged=$(ls -d */ | sed 's:\([0-9]\+\).*:\1:g' | sort -n | tail -1)
+                echo " converged in ${second_converged} iterations."
+            fi
+        fi
         
-        echo " done."
         cd $wind_directory
         touch hill.foam
 
